### ISSUE TITLE
[Building] Older version of libiio is needed

### ISSUE THREAD

**Issue by mdigiorgio** [BayLibre/iio-capture#1]
Latest version of libiio doesn't provide the `iio_create_usb_context` function anymore, in fact when trying to build `iio-capture` you get:

``` bash
$ make
cc -o iio-capture iio-capture.o  -lpthread -liio
iio-capture.o: In function `main':
~/iio-capture/iio-capture.c:472: undefined reference to `iio_create_usb_context'
collect2: error: ld returned 1 exit status
make: *** [iio-capture] Error 1
```

To able to build the tool I had to revert `libiio` to the commit [59264672be](https://github.com/analogdevicesinc/libiio/commit/59264672be6eba0e1f025d6a3eaf44f40d9db007).

**Comment by mtitinger** [comment]
Indeed, there was a recent API change in libiio. I just removed this dependency as we are not supporting any USB device right now. Many thanks,
M.
