### ISSUE TITLE
[Energy] Discrepancy in energy computation with respect to another probe

### ISSUE THREAD

**Issue by mdigiorgio** [BayLibre/iio-capture#2]
Hello,

I'm trying to use `iio-capture` in order to measure energy consumption on a device and I got very different results in the energy value with respect to what I measure with a different probe. In particular, the energy value reported by `iio-capture` is 25 times lower than what is measured by the other probe.

In order to understand which is wrong (or more accurate), I measured the energy consumption of a 2.70 Ohm resistor over which I apply a 4.03 V voltage and a current of 1.50 A for roughly 20 seconds. Therefore, the energy value should be 120.90 J.

What I measure is:
- 4.61 J with the ACME probe (Jack Power Probe)
- 101.13 J with the other probe

All the other values reported be `iio-capture` look reasonable, except for energy:

``` bash
<LAVA_SIGNAL_TESTCASE TEST_CASE_ID=vbus_max RESULT=pass UNITS=mV MEASUREMENT=4030.00>
<LAVA_SIGNAL_TESTCASE TEST_CASE_ID=energy RESULT=pass UNITS=mJ MEASUREMENT=4610.26>
<LAVA_SIGNAL_TESTCASE TEST_CASE_ID=power_min RESULT=pass UNITS=mW MEASUREMENT=6025.00>
<LAVA_SIGNAL_TESTCASE TEST_CASE_ID=power_max RESULT=pass UNITS=mW MEASUREMENT=6050.00>
<LAVA_SIGNAL_TESTCASE TEST_CASE_ID=power_avg RESULT=pass UNITS=mW MEASUREMENT=6025.02>
<LAVA_SIGNAL_TESTCASE TEST_CASE_ID=current_min RESULT=pass UNITS=mA MEASUREMENT=1496.00>
<LAVA_SIGNAL_TESTCASE TEST_CASE_ID=current_max RESULT=pass UNITS=mA MEASUREMENT=1500.00>
```

Do you have any idea why I'm getting incorrect results?

**Comment by mtitinger** [comment]
Hi Michele,

nice to hear that you got so far with ACME. The Energy computation is basically "Instant-power" times "sampling period" accumulated over each samples. It is indeed likely to be arguable as a computation. I did not expect it to be that off though. I will look into it.

**Comment by mtitinger** [comment]
The code was mainly missing to apply the scale of the power channel, hence the 1:25 ratio.
With the added patches it should be OK.

While playing with different integration time settings, I came across a glitch, but I think this is an issue driver side, maybe an integration time value that is not properly applied when writing in sysfs. Anyway, currently the sampling freq is not an option, I now set it to 114Hz so that at least 4 probes can record simultaneously with an accurate sampling rate. I will do more validation and add a sampling freq option when I get a chance.

**Comment by mdigiorgio** [comment]
Hi Marc,

OK thanks for the quick update, I will give it a try as soon as possible.

**Comment by mdigiorgio** [comment]
Nice! I can now read the correct value. Thanks for the fixes.

Also, the duration argument is a useful tool. However, sometimes the workload duration is unknown and so sending SIGTERM to stop recording is very useful. I think the default behaviour should be the previous one, where you were recording until CTRL+C is hit (you can achieve the same by setting a very long duration, but in my opinion is not very nice to have hard-coded values in the tests). What do you think?

**Comment by mtitinger** [comment]
On 02/06/2016 12:24, Michele Di Giorgio wrote:

> Nice! I can now read the correct value. Thanks for the fixes.

Cool, thanks for the update :)

> Also, the duration argument is a useful tool. However, sometimes the
> workload duration is unknown and so sending SIGTERM to stop recording is
> very useful. I think the default behaviour should be the previous one,
> where you were recording until CTRL+C is hit (you can achieve the same
> by setting a very long duration, but in my opinion is not very nice to
> have hard-coded values in the tests). What do you think?

-d/duration was for testing mainly, it should work like previously w/o 
this option, I will fix this suddenly, my bad.

BR,
M.

**Comment by mdigiorgio** [comment]
Minor issue: when printing the help you get a `(null)` in the explanation of the `--buffer-size` option:

``` bash
$ iio-capture -h
Usage:
        iio-capture [-n <hostname>] [-f <fout>] [-b <buffer-size>] [-d] [-e] [-c] [-o]<iio_device> [<channel> ...]

Options:
        -h, --help
                        Show this help and quit.
        -c, --csv
                        Output values to a Comma-Separated-Values file.
        -d, --duration
                        Duration in milli-seconds for the record (based on driver timestamps).
        -e, --energy-only
                        Oneline style output format, instead of LAVA format.
        -o, --one-line
                        Use the network backend with the provided hostname.
        -n, --network
                        Output values to specified filename as binary or CSV when '-c'.
        -f, --fout
                        Size of the capture buffer. Default is 256.
        -b, --buffer-size
                        (null)
```

You are missing the `energy-only` explanation in https://github.com/BayLibre/iio-capture/blob/master/iio-capture.c#L88

**Comment by mtitinger** [comment]
fixed, thanks.

**Comment by mdigiorgio** [comment]
Thanks for the patches..

This issue can be closed as of patchset [6559a3](https://github.com/BayLibre/iio-capture/commit/6559a3e20df784c38c592d3ac8ffa44ab1fe502a)...[8ee052](https://github.com/BayLibre/iio-capture/commit/8ee0521f2a42ab57e99269308998b12bcbe65b83)
